### ISSUE TITLE
Tight dependency ranges

### ISSUE THREAD

**Issue by qrilka** [phadej/tree-diff#10]
Your package looks cool and I wanted to use it in tests for `xlsx` library but dependency restrictions are quite high. Are they strictly required? Probably you use some features which are missing from lower versions, right?

**Comment by phadej** [comment]
As I answered you on Twitter, there are instances for classes only in `QuickCheck-2.10`, so relaxing that lower bound would mean CPP-guarding them. And because I'm paranoid, I'd like to test that configuration too.

The GHC-7.6 isn't impossible, but that require lowering `generics-sop` lower bound.

FWIW, as I see, you test `xlsx` only with `GHC-7.10` and `GHC-8.0`, `tree-diff` should work just fine for those?

**Comment by qrilka** [comment]
Probably it should some time ago I was bitten by `cabal` build failure in 7.8 probably because of newer template-haskell (the concrete error message was `ghc: internal error: stg_ap_pp_ret`) so I'd prefer to stick to stackage lts for older compilers and to use `tree-diff` I'd need up quite a lot of dependencies. So I'll close the ticket for now probably taking another look later
